# Generated by Django 5.1 on 2024-08-19 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите описание товара",
                        max_length=200,
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите цену товара",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, "Минимальная цена товара: 0.01"
                            )
                        ],
                        verbose_name="Цена товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ("-id",),
            },
        ),
    ]
